language: php
php:
  - 7.3
  - 8.0
install: composer install
script:
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage.xml
after_script:
  - bash <(curl -s https://codecov.io/bash)
